option to exclude mod motif from mzID output
smith-chem-wisc/MetaMorpheus pull request #1984
Opened 2020-11-17 20:28 UTC by rmillikin

implement option suggested in #1973

2020-11-17 20:41 UTC, zrolfs requested changes

2020-11-17 20:41 UTC, zrolfs commented on GUI/TaskWindows/SearchTaskWindow.xaml
> +                            <CheckBox x:Name="IncludeMotifInModNamesCheckBox" Margin="20 0 0 0" Content="Include motif in mod names" IsEnabled="{Binding IsChecked, ElementName=CkbMzId}" />
Can you add a tool tip explaining this is just for mzID?
Maybe put this checkbox below the decoy/contaminant checkboxes, which are likely more relevant to most users.

2020-11-20 18:03 UTC, lonelu approved these changes

2021-01-19 20:53 UTC, zrolfs approved these changes

2021-04-21 17:16 UTC, acesnik approved these changes
Haven't manually tested, but it looks like Zach did, and it looks ready to merge.

2021-04-21 18:16 UTC, acesnik commented
@rmillikin, ready to merge?

2021-04-21 21:42 UTC, merged