Add Ambiguity Level to Output
smith-chem-wisc/MetaMorpheus pull request #2058
Opened 2021-05-14 11:04 UTC by zrolfs

I wrote this so that the five-level proteoform classification would be output even when not doing a top-down search. There's still ambiguity when we do bottom-up and I think this classification system could still be useful at the peptide level.

2021-05-17 20:42 UTC, rmillikin commented
I'd like to see at least one unit test; I know the method called is tested in mzLib but the PSM/PrSM output from MM should be checked that it contains correct classifications under at least one test case. And PsmFromTsv should be checked also

2021-05-17 20:44 UTC, rmillikin requested changes
needs unit test

2021-05-17 23:03 UTC, zrolfs commented
unit test added

2021-05-18 14:26 UTC, rmillikin approved these changes

2021-05-18 19:47 UTC, rmmiller22 approved these changes

2021-05-18 19:48 UTC, merged