SpectralLibraryGenerationFirstAttempt
smith-chem-wisc/MetaMorpheus pull request #2093
Opened 2021-09-27 22:19 UTC by Yuling1996

2021-10-30 18:19 UTC, Yuling1996 commented on EngineLayer/FdrAnalysis/PEPValueAnalysisGeneric.cs
> +            float hasSpectralAngle = 0;
hasSpectralAngle will be used in IImmutableDictionary<string, int> assumedAttributeDirection, so I think it need to be a number. Did I misunderstand something ?

2021-10-30 19:10 UTC, Yuling1996 commented on TaskLayer/SearchTask/PostSearchAnalysisTask.cs
> +                        {
Yes,  a line of code was missing here. I will fix it soon

2021-11-01 21:21 UTC, Yuling1996 commented on EngineLayer/SpectralLibrarySearch/SpectralLibrarySearchFunction.cs
> +        public static List<MatchedFragmentIon> GetDecoyLibrarySpectrumFromTargetByReverse(LibrarySpectrum targetSpectrum, List<Product> decoyPeptideTheorProducts)
Does this function make sense: TestDecoyLibrarySpectraGeneration() ?

2021-11-12 19:19 UTC, kyp4 requested changes
please make it so that you cannot run MM with only a library when it requires a library and a fasta to properly run a search

2021-11-12 19:21 UTC, Yuling1996 commented
> please make it so that you cannot run MM with only a library when it requires a library and a fasta to properly run

2021-11-12 19:22 UTC, Yuling1996 commented
> > please make it so that you cannot run MM with only a library when it requires a library and a fasta to properly run

2021-11-12 19:22 UTC, Yuling1996 commented
> > > please make it so that you cannot run MM with only a library when it requires a library and a fasta to properly run

I will make changes to this. Thanks

2021-11-17 07:18 UTC, Yuling1996 commented on EngineLayer/FdrAnalysis/PEPValueAnalysisGeneric.cs
> +        {
solved

2021-11-17 07:18 UTC, Yuling1996 commented on EngineLayer/SpectralLibrarySearch/SpectralLibrarySearchFunction.cs
> +                    if (spectralLibrary != null && !peptide.Key.Protein.IsDecoy && spectralLibrary.TryGetSpectrum(peptide.Key.FullSequence, scan.PrecursorCharge, out var librarySpectrum))
solved

2022-03-23 15:35 UTC, closed without merging

2022-03-23 15:36 UTC, rmmiller22 commented
New PR was generated for spectral library content making this PR out of date