MetaDrawPolishing
smith-chem-wisc/MetaMorpheus pull request #2169
Opened 2022-08-11 18:48 UTC by nbollis

Additional Features:
Color options for background peaks and internal ions
MetaDraw specific reset defaults button
Spectrum description elements PEP and PEP-Q only show three decimals
Sort list of psms by protein name and species of origin
Filter psms by ambiguity level

Changes:
Data visualization charts now export to same folder as the rest of the images
Spectrum description 'spectral angle' field now off by default

Bug Fixes:
Resizing after psm or spectra files were reset caused a crash
Sequence annotation and stationary sequence ptm annotation positioning corrected
Export child scan as pdf now includes ptm color legend
Export sequence coverage no longer cuts off the sequence text
Sequence coverage now stays the correct size when the window is resolved

2022-08-12 19:29 UTC, Alexander-Sol requested changes
Y ions are displayed incorrectly for ambiguous peptides. Other than that, looks great!

2022-08-16 14:12 UTC, nbollis commented
> Y ions are displayed incorrectly for ambiguous peptides. Other than that, looks great!

Cannot seem to reproduce this error, could you attach the data that caused it?

2022-08-16 15:33 UTC, Alexander-Sol commented
> Cannot seem to reproduce this error, could you attach the data that caused it?

Files can be found here: https://drive.google.com/drive/folders/1QGfogd_mXcVSCRw-hzl-iwzxoex0SqIU?usp=sharing

The following peptide produces this error: EIVHIQAGQCGNQIGAK.

2022-08-18 18:37 UTC, nbollis commented
> > Cannot seem to reproduce this error, could you attach the data that caused it?
> 
> Files can be found here: https://drive.google.com/drive/folders/1QGfogd_mXcVSCRw-hzl-iwzxoex0SqIU?usp=sharing
> 
> The following peptide produces this error: EIVHIQAGQCGNQIGAK.

Bug was in the loading of the psmtsv.  Psmtsv would use the ambiguous base sequence to set the positions of the matched ions instead of only one of the possible sequences. It has been fixed

2022-08-19 14:53 UTC, Alexander-Sol approved these changes

2022-08-26 22:24 UTC, avcarr2 approved these changes
Tested it thoroughly. Works well

2022-08-31 15:14 UTC, trishorts approved these changes

2022-08-31 15:14 UTC, merged