[Waiting on Omics Merge][Waiting on MzLib Release] Deconvolution Generalization
smith-chem-wisc/MetaMorpheus pull request #2339
Opened 2024-02-09 00:02 UTC by nbollis

Enables the generalization of deconvolution to other deconvolution types in MetaMorpheus. 
This is necessary for if/when Decharge is added to MzLib.

2024-02-16 20:09 UTC, Alexander-Sol requested changes
Fix the two statements on one line and we're good to go

2024-02-22 16:34 UTC, elaboy approved these changes

2024-02-22 18:27 UTC, elaboy approved these changes

2024-02-24 20:29 UTC, YulingDai approved these changes

2024-02-27 16:00 UTC, Alexander-Sol approved these changes

2024-02-27 16:01 UTC, merged