#4 - [Waiting on Omics][Waiting on Spectral Match Generalization]Digestion params generalization
smith-chem-wisc/MetaMorpheus pull request #2341
Opened 2024-02-09 00:22 UTC by nbollis

Generalizes digestion parameters in common parameters to enable rna digestion and protein digestion

2024-03-07 21:05 UTC, trishorts commented
wherein nic embraces the var side

2024-04-19 21:18 UTC, Alexander-Sol approved these changes

2024-05-13 18:05 UTC, elaboy approved these changes

2024-08-23 21:42 UTC, acesnik approved these changes

2025-05-12 20:28 UTC, RayMSMS approved these changes

2025-05-13 17:17 UTC, Alexander-Sol commented on MetaMorpheus/EngineLayer/CrosslinkSearch/CrosslinkSearchEngine.cs
>              foreach (var id in idsOfPeptidesPossiblyObserved)
Should there be some kind of null check here? What happens if CommonParameters.DigestionParams is an RnaDigestionParams object

2025-05-13 17:29 UTC, Alexander-Sol commented on MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
> +            if (commonParams.DigestionParams is DigestionParams digestionParams)
This would be easier to understand and maintain if it was a switch statement on typeof(commonParams.DigestionParams). The current implementation assumes that there will only ever be two classes that implement IDigestionParams

2025-05-13 17:34 UTC, Alexander-Sol requested changes
Need to check for bad casts in CrosslinkSearch. 
IDigestionParams handling in MetaMorpheusTask would be better as a switch statement

2025-05-13 19:55 UTC, nbollis commented on MetaMorpheus/EngineLayer/CrosslinkSearch/CrosslinkSearchEngine.cs
>              foreach (var id in idsOfPeptidesPossiblyObserved)
I am assuming that we will not use the crosslink search engine for RNA without serious refactoring that would catch this assumption.

2025-05-13 21:00 UTC, Alexander-Sol commented on MetaMorpheus/EngineLayer/CrosslinkSearch/CrosslinkSearchEngine.cs
>              foreach (var id in idsOfPeptidesPossiblyObserved)
Would it require a serious refactor? Why can't you just use a
`if (CommonParameters.DigestionParams is not DigestionParams digestionParams)`
check and throw an exception if false?

2025-05-13 21:46 UTC, nbollis commented on MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
> +            if (commonParams.DigestionParams is DigestionParams digestionParams)
Good point. I converted this to a switch and added more FileSpecificParameter weirdness handling.

2025-05-13 21:50 UTC, nbollis commented on MetaMorpheus/EngineLayer/CrosslinkSearch/CrosslinkSearchEngine.cs
>              foreach (var id in idsOfPeptidesPossiblyObserved)
> Why can't you just use a `if (CommonParameters.DigestionParams is not DigestionParams digestionParams)` check and throw an exception if false?

That is the affect of the current implementation. I can add more explicit checks if you'd like.

2025-05-13 22:29 UTC, RayMSMS approved these changes

2025-05-15 19:31 UTC, trishorts approved these changes

2025-05-15 19:31 UTC, merged