Added precursor intensity to PSM, peptide proteoform output file
smith-chem-wisc/MetaMorpheus pull request #2365
Opened 2024-05-09 23:07 UTC by zhuoxinshi

The current psm, peptide and proteoform output reports the scan TIC as the intensity. This value is replaced in this PR by the intensity of the most abundant mz for the peptide.

2024-06-04 16:58 UTC, Alexander-Sol reviewed
You should add the new useMostAbundantPrecursorIntensity property to the SetAllFileSpecificCommonParams method in MetaMorpheusTask

2024-06-12 18:38 UTC, Alexander-Sol approved these changes

2024-06-12 18:48 UTC, Alexander-Sol reviewed
It might be useful to record the m/z and intensity of the most abundant precursor. Maybe that can be saved for a future PR

2024-06-12 18:48 UTC, Alexander-Sol commented on MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
> +                                    precursors.Add((monoPeakMz, envelope.Charge, intensity, peakCount));
Should you also store which m/z has the highest intensity? I feel like you might want that information later

2024-06-13 18:37 UTC, nbollis approved these changes

2024-06-13 19:40 UTC, avcarr2 requested changes

2024-06-13 19:40 UTC, avcarr2 commented on MetaMorpheus/EngineLayer/PsmTsv/PsmFromTsv.cs
> +            PrecursorIntensity = (parsedHeader[PsmTsvHeader.PrecursorIntensity] < 0) ? null : (double?)double.Parse(spl[parsedHeader[PsmTsvHeader.PrecursorIntensity]].Trim(), CultureInfo.InvariantCul
Would Int.TryParse() work better for this than the current implementation? That way if there is invalid input, the method would return false, and you can handle the invalid input from there.

2024-06-13 20:27 UTC, nbollis commented on MetaMorpheus/EngineLayer/Ms2ScanWithSpecificMass.cs
> +        public Ms2ScanWithSpecificMass(MsDataScan mzLibScan, double precursorMonoisotopicPeakMz, int precursorCharge, string fullFilePath, CommonParameters commonParam,
This one is a simple line wrap to improve readability

2024-06-17 13:22 UTC, trishorts approved these changes

2024-06-17 13:24 UTC, merged