Kdn adding and diagnostic filtering
smith-chem-wisc/MetaMorpheus pull request #2383
Opened 2024-07-03 17:01 UTC by RayMSMS

1. Add Kdn sugar type in the dictionary
2. Add a new function "DiagnosticIon filter", which uses the diagnostic ion to distinguish the isobaric peak.
    If we find 274/292 peak in Scan, we remove the glycan without A(NeuAc) in the candidate list.
3. Add the corresponding test for the filter function. Isobaric case: H1N1A1 & N2K1.

2024-07-18 17:00 UTC, nbollis requested changes
Looks good overall. I had a few questions and concerns that I left as comments throughout the PR. I also checked the code coverage and did not find an area where it would be easy to test the additions that you made.

2024-07-22 20:24 UTC, RayMSMS commented on MetaMorpheus/EngineLayer/Glycan_Mods/OGlycan/Bullfrog 64 O-glycan wKdn corrected_convert.txt
I just added to the existing glyco files. The Glycan_Mods is a default glycan database collection for the user.

2024-07-22 20:57 UTC, RayMSMS commented on MetaMorpheus/EngineLayer/GlycoSearch/GlycanDatabase.cs
> +                                GlycanIon add_fuc_glycanIon = ExtendGlycanIon(hexose_glycanIon, 0, 0, 1, 0, glycan_mass);
The fragment is for N-glycan fragmentation, we don't use that in O-pair search right now. But, I still do a small revision to correct the fragment issue. A tester is also built.

2024-07-23 21:16 UTC, RayMSMS commented on MetaMorpheus/EngineLayer/GlycoSearch/GlycoSearchEngine.cs
> +        protected readonly List<GlycoSpectralMatch>[] GlobalCsms;  // Why don't we call it GlobalGsms?
Got it. I already changed it.

2024-07-23 21:18 UTC, RayMSMS commented on MetaMorpheus/EngineLayer/GlycoSearch/GlycoSpectralMatch.cs
> +            Dictionary<string, int> ModSiteSeenCount = new Dictionary<string, int>(); // all possible glycan-sites pair, Dictionary<string, int>: site-glycan pair, count
Got it. Corrected it.

2024-07-30 16:12 UTC, RayMSMS commented on MetaMorpheus/EngineLayer/GlycoSearch/GlycanBox.cs
>          public GlycanBox(int[] ids, bool targetDecoy = true):base(ids)
Corrected it. Thanks

2024-07-30 16:49 UTC, trishorts approved these changes

2024-07-30 17:45 UTC, Alexander-Sol approved these changes

2024-08-02 19:20 UTC, nbollis approved these changes

2024-08-02 19:20 UTC, merged