Changes to PEP Calculation and Filtering
smith-chem-wisc/MetaMorpheus pull request #2387
Opened 2024-07-24 18:28 UTC by Alexander-Sol

There have been several iterations of this guy, but all the tests are finally passing. See also PR 2376

 

> Currently, the pep q-value is computed by summing the pep and dividing by row number for psms or peptides sorted in descending order by MetaMorpheus score.
> 
> In this PR, pep is used to re-score the psms/peptides. PSMs are sorted in ascending order (good to bad) and then pep q-value is computed from bottom to top like we recently did for q-value using the formula (cumulative decoy count + 1) / cumulative target count).

2024-07-29 17:14 UTC, Alexander-Sol commented
![image (3)](https://github.com/user-attachments/assets/2a350091-6314-4ae6-a276-a2795850adb7)

These are the results from a search @trishorts ran using an arabidopsis entrapment database

2024-07-30 16:48 UTC, trishorts approved these changes

2024-07-31 01:06 UTC, nbollis requested changes
Comments and questions

2024-07-31 01:06 UTC, nbollis commented on MetaMorpheus/EngineLayer/FdrAnalysis/FdrAnalysisEngine.cs
> +                        CalculateQValue(peptides, peptideLevelCalculation: true, pepCalculation: false);
Are these comments up to date?

2024-07-31 16:12 UTC, Alexander-Sol commented on MetaMorpheus/TaskLayer/MetaMorpheusTask.cs
> +                    output.WriteLine(psm.ToString(modstoWritePruned, writePsmNotPeptideFdrInfo));
Yes! Good catch

2024-08-02 19:05 UTC, trishorts approved these changes

2024-08-02 19:05 UTC, trishorts approved these changes

2024-08-05 16:57 UTC, nbollis approved these changes

2024-08-05 18:23 UTC, merged