Q value threshold adjustment and bug fix
smith-chem-wisc/MetaMorpheus pull request #2426
Opened 2024-10-15 19:54 UTC by trishorts

![image](https://github.com/user-attachments/assets/9d419e06-a7bb-4fb9-afce-e5acbf5ffdef)

2024-10-18 17:01 UTC, Alexander-Sol approved these changes

2024-10-18 17:12 UTC, Alexander-Sol requested changes
the QvalueThresholdOverride property and associated field are a little wonky, I suggest changing it to a property with public get; private set;, then changing it in the relevant tests using reflection. Also, add the non-parallelizable tags

2024-10-30 17:37 UTC, nbollis submitted a review, later dismissed

2024-11-04 17:46 UTC, elaboy submitted a review, later dismissed

2024-11-07 00:41 UTC, nbollis approved these changes

2024-11-07 17:53 UTC, elaboy approved these changes

2024-11-07 18:21 UTC, Alexander-Sol approved these changes
Looks good

2024-11-07 19:08 UTC, merged